<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['name' => 'Afganistán', 'capital' => 'Kabul', 'sigla' => 'AF'],
            ['name' => 'Albania', 'capital' => 'Tirana', 'sigla' => 'AL'],
            ['name' => 'Alemania', 'capital' => 'Berlín', 'sigla' => 'DE'],
            ['name' => 'Andorra', 'capital' => 'Andorra la Vieja', 'sigla' => 'AD'],
            ['name' => 'Angola', 'capital' => 'Luanda', 'sigla' => 'AO'],
            ['name' => 'Antigua y Barbuda', 'capital' => 'Saint John', 'sigla' => 'AG'],
            ['name' => 'Arabia Saudita', 'capital' => 'Riad', 'sigla' => 'SA'],
            ['name' => 'Argelia', 'capital' => 'Argel', 'sigla' => 'DZ'],
            ['name' => 'Argentina', 'capital' => 'Buenos Aires', 'sigla' => 'AR'],
            ['name' => 'Armenia', 'capital' => 'Ereván', 'sigla' => 'AM'],
            ['name' => 'Australia', 'capital' => 'Canberra', 'sigla' => 'AU'],
            ['name' => 'Austria', 'capital' => 'Viena', 'sigla' => 'AT'],
            ['name' => 'Azerbaiyán', 'capital' => 'Bakú', 'sigla' => 'AZ'],
            ['name' => 'Bahamas', 'capital' => 'Nasáu', 'sigla' => 'BS'],
            ['name' => 'Bangladés', 'capital' => 'Daca', 'sigla' => 'BD'],
            ['name' => 'Barbados', 'capital' => 'Bridgetown', 'sigla' => 'BB'],
            ['name' => 'Baréin', 'capital' => 'Manama', 'sigla' => 'BH'],
            ['name' => 'Bélgica', 'capital' => 'Bruselas', 'sigla' => 'BE'],
            ['name' => 'Belice', 'capital' => 'Belmopán', 'sigla' => 'BZ'],
            ['name' => 'Benín', 'capital' => 'Porto-Novo', 'sigla' => 'BJ'],
            ['name' => 'Bielorrusia', 'capital' => 'Minsk', 'sigla' => 'BY'],
            ['name' => 'Birmania', 'capital' => 'Naipyidó', 'sigla' => 'MM'],
            ['name' => 'Bolivia', 'capital' => 'Sucre', 'sigla' => 'BO'],
            ['name' => 'Bosnia-Herzegovina', 'capital' => 'Sarajevo', 'sigla' => 'BA'],
            ['name' => 'Botsuana', 'capital' => 'Gaborone', 'sigla' => 'BW'],
            ['name' => 'Brasil', 'capital' => 'Brasilia', 'sigla' => 'BR'],
            ['name' => 'Brunéi', 'capital' => 'Bandar Seri Begawan', 'sigla' => 'BN'],
            ['name' => 'Bulgaria', 'capital' => 'Sofía', 'sigla' => 'BG'],
            ['name' => 'Burkina', 'capital' => 'Uagadugú', 'sigla' => 'BF'],
            ['name' => 'Burundi', 'capital' => 'Buyumbura', 'sigla' => 'BI'],
            ['name' => 'Bután', 'capital' => 'Thimphu', 'sigla' => 'BT'],
            ['name' => 'Cabo Verde', 'capital' => 'Praia', 'sigla' => 'CV'],
            ['name' => 'Camboya', 'capital' => 'Nom Pen', 'sigla' => 'KH'],
            ['name' => 'Camerún', 'capital' => 'Yaundé', 'sigla' => 'CM'],
            ['name' => 'Canadá', 'capital' => 'Ottawa', 'sigla' => 'CA'],
            ['name' => 'Catar', 'capital' => 'Doha', 'sigla' => 'QA'],
            ['name' => 'Chad', 'capital' => 'Yamena', 'sigla' => 'TD'],
            ['name' => 'Chile', 'capital' => 'Santiago', 'sigla' => 'CL'],
            ['name' => 'China', 'capital' => 'Pekín', 'sigla' => 'CN'],
            ['name' => 'Chipre', 'capital' => 'Nicosia', 'sigla' => 'CY'],
            ['name' => 'Colombia', 'capital' => 'Bogotá', 'sigla' => 'CO'],
            ['name' => 'Comoras', 'capital' => 'Moroni', 'sigla' => 'KM'],
            ['name' => 'Congo', 'capital' => 'Brazzaville', 'sigla' => 'CG'],
            ['name' => 'Corea del Norte', 'capital' => 'Pionyang', 'sigla' => 'KP'],
            ['name' => 'Corea del Sur', 'capital' => 'Seúl', 'sigla' => 'KR'],
            ['name' => 'Costa de Marfil', 'capital' => 'Yamusukro', 'sigla' => 'CI'],
            ['name' => 'Costa Rica', 'capital' => 'José', 'sigla' => 'CR'],
            ['name' => 'Croacia', 'capital' => 'Zagreb', 'sigla' => 'HR'],
            ['name' => 'Cuba', 'capital' => 'La Habana', 'sigla' => 'CU'],
            ['name' => 'Dinamarca', 'capital' => 'Copenhague', 'sigla' => 'DK'],
            ['name' => 'Dominica', 'capital' => 'Roseau', 'sigla' => 'DM'],
            ['name' => 'Ecuador', 'capital' => 'Quito', 'sigla' => 'EC'],
            ['name' => 'Egipto', 'capital' => 'El Cairo', 'sigla' => 'EG'],
            ['name' => 'El Salvador', 'capital' => 'San Salvador', 'sigla' => 'SV'],
            ['name' => 'Emiratos Árabes Unidos', 'capital' => 'Abu Dabi', 'sigla' => 'AE'],
            ['name' => 'Eritrea', 'capital' => 'Asmara', 'sigla' => 'ER'],
            ['name' => 'Eslovaquia', 'capital' => 'Bratislava', 'sigla' => 'SK'],
            ['name' => 'Eslovenia', 'capital' => 'Liubliana', 'sigla' => 'SI'],
            ['name' => 'España', 'capital' => 'Madrid', 'sigla' => 'ES'],
            ['name' => 'Estados Unidos', 'capital' => 'Washington D. C.', 'sigla' => 'US'],
            ['name' => 'Estonia', 'capital' => 'Tallin', 'sigla' => 'EE'],
            ['name' => 'Esuatini', 'capital' => 'Mbabane', 'sigla' => 'SZ'],
            ['name' => 'Etiopía', 'capital' => 'Adís Abeba', 'sigla' => 'ET'],
            ['name' => 'Filipinas', 'capital' => 'Manila', 'sigla' => 'PH'],
            ['name' => 'Finlandia', 'capital' => 'Helsinki', 'sigla' => 'FI'],
            ['name' => 'Fiyi', 'capital' => 'Suva', 'sigla' => 'FJ'],
            ['name' => 'Francia', 'capital' => 'París', 'sigla' => 'FR'],
            ['name' => 'Gabón', 'capital' => 'Libreville', 'sigla' => 'GA'],
            ['name' => 'Gambia', 'capital' => 'Banjul', 'sigla' => 'GM'],
            ['name' => 'Georgia', 'capital' => 'Tiflis', 'sigla' => 'GE'],
            ['name' => 'Ghana', 'capital' => 'Accra', 'sigla' => 'GH'],
            ['name' => 'Granada', 'capital' => 'Saint George', 'sigla' => 'GD'],
            ['name' => 'Grecia', 'capital' => 'Atenas', 'sigla' => 'GR'],
            ['name' => 'Guatemala', 'capital' => 'Guatemala', 'sigla' => 'GT'],
            ['name' => 'Guinea', 'capital' => 'Conakri', 'sigla' => 'GN'],
            ['name' => 'Guinea Ecuatorial', 'capital' => 'Malabo', 'sigla' => 'GQ'],
            ['name' => 'Guinea-Bisáu', 'capital' => 'Bisáu', 'sigla' => 'GW'],
            ['name' => 'Guyana', 'capital' => 'Georgetown', 'sigla' => 'GY'],
            ['name' => 'Haití', 'capital' => 'Puerto Príncipe', 'sigla' => 'HT'],
            ['name' => 'Honduras', 'capital' => 'Tegucigalpa', 'sigla' => 'HN'],
            ['name' => 'Hungría', 'capital' => 'Budapest', 'sigla' => 'HU'],
            ['name' => 'India', 'capital' => 'Nueva Delhi', 'sigla' => 'IN'],
            ['name' => 'Indonesia', 'capital' => 'Yakarta', 'sigla' => 'ID'],
            ['name' => 'Irak', 'capital' => 'Bagdad', 'sigla' => 'IR'],
            ['name' => 'Irán', 'capital' => 'Teherán', 'sigla' => 'IQ'],
            ['name' => 'Irlanda', 'capital' => 'Dublín', 'sigla' => 'IE'],
            ['name' => 'Islandia', 'capital' => 'Reikiavik', 'sigla' => 'IS'],
            ['name' => 'Islas Marshall', 'capital' => 'Majuro', 'sigla' => 'MH'],
            ['name' => 'Islas Salomón', 'capital' => 'Honiara', 'sigla' => 'SB'],
            ['name' => 'Israel', 'capital' => 'Jerusalén', 'sigla' => 'IL'],
            ['name' => 'Italia', 'capital' => 'Roma', 'sigla' => 'IT'],
            ['name' => 'Jamaica', 'capital' => 'Kingston', 'sigla' => 'JM'],
            ['name' => 'Japón', 'capital' => 'Tokio', 'sigla' => 'JP'],
            ['name' => 'Jordania', 'capital' => 'Amán', 'sigla' => 'JO'],
            ['name' => 'Kazajistán', 'capital' => 'Astaná', 'sigla' => 'KZ'],
            ['name' => 'Kenia', 'capital' => 'Nairobi', 'sigla' => 'KE'],
            ['name' => 'Kirguistán', 'capital' => 'Biskek', 'sigla' => 'KG'],
            ['name' => 'Kiribati', 'capital' => 'Tarawa', 'sigla' => 'KI'],
            ['name' => 'Kosovo', 'capital' => 'Pristina', 'sigla' => 'XK'],
            ['name' => 'Kuwait', 'capital' => 'Kuwait City', 'sigla' => 'KW'],
            ['name' => 'Laos', 'capital' => 'Vientián', 'sigla' => 'LA'],
            ['name' => 'Lesoto', 'capital' => 'Maseru', 'sigla' => 'LS'],
            ['name' => 'Letonia', 'capital' => 'Riga', 'sigla' => 'LV'],
            ['name' => 'Líbano', 'capital' => 'Beirut', 'sigla' => 'LB'],
            ['name' => 'Liberia', 'capital' => 'Monrovia', 'sigla' => 'LR'],
            ['name' => 'Libia', 'capital' => 'Trípoli', 'sigla' => 'LY'],
            ['name' => 'Liechtenstein', 'capital' => 'Vaduz', 'sigla' => 'LI'],
            ['name' => 'Lituania', 'capital' => 'Vilna', 'sigla' => 'LT'],
            ['name' => 'Luxemburgo', 'capital' => 'Luxemburgo', 'sigla' => 'LU'],
            ['name' => 'Macedonia del Norte', 'capital' => 'Skopie', 'sigla' => 'MK'],
            ['name' => 'Madagascar', 'capital' => 'Antananarivo', 'sigla' => 'MG'],
            ['name' => 'Malasia', 'capital' => 'Kuala Lumpur', 'sigla' => 'MY'],
            ['name' => 'Malaui', 'capital' => 'Lilongüe', 'sigla' => 'MW'],
            ['name' => 'Maldivas', 'capital' => 'Malé', 'sigla' => 'MV'],
            ['name' => 'Malí', 'capital' => 'Bamako', 'sigla' => 'ML'],
            ['name' => 'Malta', 'capital' => 'La Valeta', 'sigla' => 'MT'],
            ['name' => 'Marruecos', 'capital' => 'Rabat', 'sigla' => 'MA'],
            ['name' => 'Mauricio', 'capital' => 'Port Louis', 'sigla' => 'MU'],
            ['name' => 'Mauritania', 'capital' => 'Nuakchot', 'sigla' => 'MR'],
            ['name' => 'México', 'capital' => 'México', 'sigla' => 'MX'],
            ['name' => 'Micronesia', 'capital' => 'Palikir', 'sigla' => 'FM'],
            ['name' => 'Moldavia', 'capital' => 'Chisináu', 'sigla' => 'MD'],
            ['name' => 'Mónaco', 'capital' => 'Mónaco', 'sigla' => 'MC'],
            ['name' => 'Mongolia', 'capital' => 'Ulán Bator', 'sigla' => 'MN'],
            ['name' => 'Montenegro', 'capital' => 'Podgorica', 'sigla' => 'ME'],
            ['name' => 'Mozambique', 'capital' => 'Maputo', 'sigla' => 'MZ'],
            ['name' => 'Namibia', 'capital' => 'Windhoek', 'sigla' => 'NA'],
            ['name' => 'Nauru', 'capital' => 'Yaren', 'sigla' => 'NR'],
            ['name' => 'Nepal', 'capital' => 'Katmandú', 'sigla' => 'NP'],
            ['name' => 'Nicaragua', 'capital' => 'Managua', 'sigla' => 'NI'],
            ['name' => 'Níger', 'capital' => 'Niamey', 'sigla' => 'NE'],
            ['name' => 'Nigeria', 'capital' => 'Abuya', 'sigla' => 'NG'],
            ['name' => 'Noruega', 'capital' => 'Oslo', 'sigla' => 'NO'],
            ['name' => 'Nueva Zelanda', 'capital' => 'Wellington', 'sigla' => 'NZ'],
            ['name' => 'Omán', 'capital' => 'Mascate', 'sigla' => 'OM'],
            ['name' => 'Países Bajos', 'capital' => 'Ámsterdam', 'sigla' => 'NL'],
            ['name' => 'Pakistán', 'capital' => 'Islamabad', 'sigla' => 'PK'],
            ['name' => 'Palaos', 'capital' => 'Melekeok', 'sigla' => 'PW'],
            ['name' => 'Palestina', 'capital' => 'Jerusalén Este', 'sigla' => 'PS'],
            ['name' => 'Panamá', 'capital' => 'Panamá', 'sigla' => 'PA'],
            ['name' => 'Papúa Nueva Guinea', 'capital' => 'Puerto Moresby', 'sigla' => 'PG'],
            ['name' => 'Paraguay', 'capital' => 'Asunción', 'sigla' => 'PY'],
            ['name' => 'Perú', 'capital' => 'Lima', 'sigla' => 'PE'],
            ['name' => 'Polonia', 'capital' => 'Varsovia', 'sigla' => 'PL'],
            ['name' => 'Portugal', 'capital' => 'Lisboa', 'sigla' => 'PT'],
            ['name' => 'Reino Unido', 'capital' => 'Londres', 'sigla' => 'PR'],
            ['name' => 'República Centroafricana', 'capital' => 'Bangui', 'sigla' => 'CF'],
            ['name' => 'República Checa', 'capital' => 'Praga', 'sigla' => 'CZ'],
            ['name' => 'República Democrática del Congo', 'capital' => 'Kinsasa', 'sigla' => 'CD'],
            ['name' => 'República Dominicana', 'capital' => 'Santo Domingo', 'sigla' => 'DO'],
            ['name' => 'Ruanda', 'capital' => 'Kigali', 'sigla' => 'RW'],
            ['name' => 'Rumania', 'capital' => 'Bucarest', 'sigla' => 'RO'],
            ['name' => 'Rusia', 'capital' => 'Moscú', 'sigla' => 'RU'],
            ['name' => 'Samoa', 'capital' => 'Apia', 'sigla' => 'WS'],
            ['name' => 'San Cristóbal y Nieves', 'capital' => 'Basseterre', 'sigla' => 'KN'],
            ['name' => 'San Marino', 'capital' => 'San Marino', 'sigla' => 'SM'],
            ['name' => 'San Vicente y las Granadinas', 'capital' => 'Kingstown', 'sigla' => 'VC'],
            ['name' => 'Santa Lucía', 'capital' => 'Castries', 'sigla' => 'LC'],
            ['name' => 'Santo Tomé y Príncipe', 'capital' => 'Santo Tomé', 'sigla' => 'ST'],
            ['name' => 'Senegal', 'capital' => 'Dakar', 'sigla' => 'SN'],
            ['name' => 'Serbia', 'capital' => 'Belgrado', 'sigla' => 'RS'],
            ['name' => 'Seychelles', 'capital' => 'Victoria', 'sigla' => 'SC'],
            ['name' => 'Sierra Leona', 'capital' => 'Freetown', 'sigla' => 'SL'],
            ['name' => 'Singapur', 'capital' => 'Singapur', 'sigla' => 'SG'],
            ['name' => 'Siria', 'capital' => 'Damasco', 'sigla' => 'SY'],
            ['name' => 'Somalia', 'capital' => 'Mogadiscio', 'sigla' => 'SO'],
            ['name' => 'Sri Lanka', 'capital' => 'Sri Jayawardenapura Kotte', 'sigla' => 'LK'],
            ['name' => 'Sudáfrica', 'capital' => 'Pretoria', 'sigla' => 'ZA'],
            ['name' => 'Sudán', 'capital' => 'Jartum', 'sigla' => 'SD'],
            ['name' => 'Sudán del Sur', 'capital' => 'Yuba', 'sigla' => 'SS'],
            ['name' => 'Suecia', 'capital' => 'Estocolmo', 'sigla' => 'SE'],
            ['name' => 'Suiza', 'capital' => 'Berna', 'sigla' => 'CH'],
            ['name' => 'Surinam', 'capital' => 'Paramaribo', 'sigla' => 'SR'],
            ['name' => 'Tailandia', 'capital' => 'Bangkok', 'sigla' => 'TH'],
            ['name' => 'Taiwán', 'capital' => 'Taipéi', 'sigla' => 'TW'],
            ['name' => 'Tanzania', 'capital' => 'Dodoma', 'sigla' => 'TZ'],
            ['name' => 'Tayikistán', 'capital' => 'Dusambé', 'sigla' => 'TJ'],
            ['name' => 'Timor Oriental', 'capital' => 'Dili', 'sigla' => 'TL'],
            ['name' => 'Togo', 'capital' => 'Lomé', 'sigla' => 'TG'],
            ['name' => 'Tonga', 'capital' => 'Nukualofa', 'sigla' => 'TO'],
            ['name' => 'Trinidad y Tobago', 'capital' => 'Puerto España', 'sigla' => 'TT'],
            ['name' => 'Túnez', 'capital' => 'Túnez', 'sigla' => 'TN'],
            ['name' => 'Turkmenistán', 'capital' => 'Asjabad', 'sigla' => 'TM'],
            ['name' => 'Turquía', 'capital' => 'Ankara', 'sigla' => 'TR'],
            ['name' => 'Tuvalu', 'capital' => 'Funafuti', 'sigla' => 'TV'],
            ['name' => 'Ucrania', 'capital' => 'Kiev', 'sigla' => 'UA'],
            ['name' => 'Uganda', 'capital' => 'Kampala', 'sigla' => 'UG'],
            ['name' => 'Uruguay', 'capital' => 'Montevideo', 'sigla' => 'UY'],
            ['name' => 'Uzbekistán', 'capital' => 'Taskent', 'sigla' => 'UZ'],
            ['name' => 'Vanuatu', 'capital' => 'Port Vila', 'sigla' => 'VU'],
            ['name' => 'Vaticano', 'capital' => 'Vaticano', 'sigla' => 'VA'],
            ['name' => 'Venezuela', 'capital' => 'Caracas', 'sigla' => 'VE'],
            ['name' => 'Vietnam', 'capital' => 'Hanói', 'sigla' => 'VN'],
            ['name' => 'Yemen', 'capital' => 'Saná', 'sigla' => 'YE'],
            ['name' => 'Yibuti', 'capital' => 'Yibuti', 'sigla' => 'DJ'],
            ['name' => 'Zambia', 'capital' => 'Lusaka', 'sigla' => 'ZM'],
            ['name' => 'Zimbabue', 'capital' => 'Harare', 'sigla' => 'ZW'],
        ]);
        
    }
}
